<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>camera_cpp</name>
  <version>0.1.0</version>
  <description>ROS2 driver for streaming a GoPro camera (in webcam mode) as image and camera_info topics, with latency-corrected timestamps.</description>
  <maintainer email="sandeepzachariah123@gmail.com">Sandeep Zachariah</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>ament_index_cpp</depend>
  <depend>OpenCV</depend>
  <depend>yaml-cpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
